class NotificationHandle:
	def id(self) -> int: ...


class Notification:
	def appname(self, appname: str) -> Notification: ...
	def summary(self, summary: str) -> Notification: ...
	def subtitle(self, subtitle: str) -> Notification: ...
	def image_path(self, path: str) -> Notification: ...
	def sound_name(self, name: str) -> Notification: ...
	def body(self, body: str) -> Notification: ...
	def icon(self, icon: str) -> Notification: ...
	def auto_icon(self) -> Notification: ...
	def timeout(self, timeout: int) -> Notification: ...
	def urgency(self, urgency: int) -> Notification: ...
	def id(self, id: int) -> Notification: ...
	def finalize(self) -> Notification: ...
	def show(self) -> NotificationHandle: ...